POST https://sso.auth.mparticle.com/oauth/token
Content-Type: application/json

{
  "client_id": "91OqQRqyrwwDraR72trbwZDhEIiAKEQ8",
  "client_secret": "-0IEj_Csj5-z_xaXY-AN5S6H1-CR0ugG83A2r0bkT7eu3aOV9RWov3yxq8uxmj1M",
  "audience": "https://api.mparticle.com",
  "grant_type": "client_credentials"
}

###
GET https://api.mparticle.com/userprofile/v1/3000055/93/201/2607556348556493891?fields=device_identities,user_identities,user_attributes,audience_memberships,attribution
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1qRXhRMFZFUWtJMFFqSXdRekZEUlRNeVF6RkNOVVJCUVRkR1JrSTFRVFkwUTBNME5ETTVOQSJ9.eyJodHRwczovL21wYXJ0aWNsZS5jb20vY2xhaW1zL3N1YmplY3RuYW1lIjoiY2xpZW50X2lkOjkxT3FRUnF5cnd3RHJhUjcydHJid1pEaEVJaUFLRVE4IiwiaHR0cHM6Ly9tcGFydGljbGUuY29tL2NsYWltcy9wb2QiOiJhdTEiLCJpc3MiOiJodHRwczovL3Nzby5hdXRoLm1wYXJ0aWNsZS5jb20vIiwic3ViIjoiOTFPcVFScXlyd3dEcmFSNzJ0cmJ3WkRoRUlpQUtFUThAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vYXBpLm1wYXJ0aWNsZS5jb20iLCJpYXQiOjE2ODQyODM2NTMsImV4cCI6MTY4NDMxMjQ1MywiYXpwIjoiOTFPcVFScXlyd3dEcmFSNzJ0cmJ3WkRoRUlpQUtFUTgiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.bTR11yIybjxeVkL8gvC5fjv2_Mv8zbkHmMiHY13_VWjCM3a1MFGBm_ZqgE3luiWWMR0FgAy3IOjXJ6H2GQEOBWcGgqRd6kn2W_Kz4kfSYoSbb2VL0-a8zO8TLmprKo1YX6YcDYZ_9QBlT83YcHvwEQ8qUK5mxpn0PmnjquZwbRvW3R-pBrtWcNUki3mBNChaB1WFnlkWU2tnstCXUGlK5QFpXlcGWYJoWoVxj4PUjjeBJ1ITec5OiiiJZIiID69JYxJE6oSdgrsm1gxLrlfDdi1WJUDpLaDuxHUl1XGGGnOlkODuxgel71N2cIkHpY13VN09zbrnbncsZ5Hb85P9Yw

